{-# LANGUAGE CPP, TemplateHaskell #-}
module IdeSession.RPC.Client (
    RpcServer
  , RpcConversation(..)
  , forkRpcServer
  , connectToRpcServer
  , rpc
  , rpcConversation
  , shutdown
  , forceShutdown
  , ExternalException(..)
  , illscopedConversationException
  , serverKilledException
  , getRpcExitCode
  ) where

import Control.Applicative ((<$>))
import Control.Concurrent.MVar (MVar, newMVar, tryTakeMVar)
import qualified Control.Exception as Ex
import Control.Monad (unless, void, when)
import Data.Binary (Binary, decode, encode)
import qualified Data.ByteString.Lazy.Char8 as BSL
import Data.IORef (newIORef, readIORef, writeIORef)
import Data.Typeable (Typeable)
import GHC.IO.Handle.FD (openFileBlocking)
import Prelude hiding (take)
import System.Directory (canonicalizePath, executable, getPermissions)
import System.Exit (ExitCode)
import System.IO (Handle, IOMode (..), writeFile)
import System.Posix.IO (closeFd, createPipe, fdToHandle)
import System.Posix.Signals (sigKILL, signalProcess)
import System.Posix.Types (Fd)
import System.Process (CreateProcess (cwd, env), ProcessHandle, createProcess,
                       getProcessExitCode, proc, waitForProcess)
import System.Process.Internals (ProcessHandle__ (..), withProcessHandle)

import IdeSession.RPC.API
import IdeSession.RPC.Stream
import IdeSession.Util.BlockingOps

--------------------------------------------------------------------------------
-- Client-side API                                                            --
--------------------------------------------------------------------------------

-- | Abstract data type representing RPC servers
data RpcServer = RpcServer {
    -- | Handle to write requests to
    rpcRequestW  :: Handle
    -- | Handle to read server errors from
  , rpcErrorsR   :: Handle
    -- | Handle on the server process itself
    --
    -- This is Nothing if we connected to an existing RPC server
    -- ('connectToRpcServer') rather than started a new server
    -- ('forkRpcServer')
  , rpcProc      :: Maybe ProcessHandle
    -- | IORef containing the server response stream
  , rpcResponseR :: Stream Response
    -- | Server state
  , rpcState     :: MVar RpcClientSideState
  }

-- | RPC server state
data RpcClientSideState =
    -- | The server is running.
    RpcRunning
    -- | The server was stopped, either manually or because of an exception
  | RpcStopped Ex.SomeException

-- | Fork an RPC server as a separate process
--
-- @forkRpcServer exec args@ starts executable @exec@ with arguments
-- @args ++ args'@ where @args'@ are internal arguments generated by
-- 'forkRpcServer'. These internal arguments should be passed as arguments
-- to 'rpcServer'.
--
-- As a typical example, you might pass @["--server"]@ as @args@, and the
-- 'main' function of @exec@ might look like
--
-- > main = do
-- >   args <- getArgs
-- >   case args of
-- >     "--server" : args' ->
-- >       rpcServer args' <<your request handler>>
-- >     _ ->
-- >       <<deal with other cases>>
forkRpcServer :: FilePath        -- ^ Filename of the executable
              -> [String]        -- ^ Arguments
              -> Maybe FilePath  -- ^ Working directory
              -> Maybe [(String, String)] -- ^ Environment
              -> IO RpcServer
forkRpcServer path args workingDir menv = do
  (requestR,  requestW)  <- createPipe
  (responseR, responseW) <- createPipe
  (errorsR,   errorsW)   <- createPipe

  let showFd :: Fd -> String
      showFd fd = show (fromIntegral fd :: Int)

  let args' = args ++ map showFd [ requestR,  requestW
                                 , responseR, responseW
                                 , errorsR,   errorsW
                                 ]

  fullPath <- pathToExecutable path
  (Nothing, Nothing, Nothing, ph) <- createProcess (proc fullPath args') {
                                         cwd = workingDir,
                                         env = menv
                                       }

  -- Close the ends of the pipes that we're not using, and convert the rest
  -- to handles
  closeFd requestR
  closeFd responseW
  closeFd errorsW
  requestW'  <- fdToHandle requestW
  responseR' <- fdToHandle responseR
  errorsR'   <- fdToHandle errorsR

  st    <- newMVar RpcRunning
  input <- newStream responseR'
  return RpcServer {
      rpcRequestW  = requestW'
    , rpcErrorsR   = errorsR'
    , rpcProc      = Just ph
    , rpcState     = st
    , rpcResponseR = input
    }
  where
    pathToExecutable :: FilePath -> IO FilePath
    pathToExecutable relPath = do
      fullPath    <- canonicalizePath relPath
      permissions <- getPermissions fullPath
      if executable permissions
        then return fullPath
        else Ex.throwIO . userError $ relPath ++ " not executable"

-- | Connect to an existing RPC server
--
-- It is the responsibility of the caller to make sure that each triplet
-- of named pipes is only used for RPC connection.
connectToRpcServer :: FilePath   -- ^ stdin named pipe
                   -> FilePath   -- ^ stdout named pipe
                   -> FilePath   -- ^ stderr named pipe
                   -> IO RpcServer
connectToRpcServer requestW responseR errorsR = do
  -- TODO: here and in forkRpcServer, deal with exceptions
  requestW'  <- openFileBlocking requestW  WriteMode
  responseR' <- openFileBlocking responseR ReadMode
  errorsR'   <- openFileBlocking errorsR   ReadMode
  st         <- newMVar RpcRunning
  input      <- newStream responseR'
  return RpcServer {
      rpcRequestW  = requestW'
    , rpcErrorsR   = errorsR'
    , rpcProc      = Nothing
    , rpcState     = st
    , rpcResponseR = input
    }

-- | Specialized form of 'rpcConversation' to do single request and wait for
-- a single response.
rpc :: (Typeable req, Typeable resp, Binary req, Binary resp) => RpcServer -> req -> IO resp
rpc server req = rpcConversation server $ \RpcConversation{..} -> put req >> get

-- | Run an RPC conversation. If the handler throws an exception during
-- the conversation the server is terminated.
rpcConversation :: RpcServer
                -> (RpcConversation -> IO a)
                -> IO a
rpcConversation server handler = withRpcServer server False $ \st ->
  case st of
    RpcRunning -> do
      -- We want to be able to detect when a conversation is used out of scope
      inScope <- newIORef True

      -- Call the handler, update the state, and return the result
      a <- handler . conversation $ do isInScope <- readIORef inScope
                                       unless isInScope $
                                         Ex.throwIO illscopedConversationException

      -- Record that the conversation is no longer in scope and return
      writeIORef inScope False
      return (RpcRunning, a)
    RpcStopped ex ->
      Ex.throwIO ex
  where
    conversation :: IO () -> RpcConversation
    conversation verifyScope = RpcConversation {
        put = \req -> do
                 verifyScope
                 mapIOToExternal server $ do
                   let msg = encode $ Request (IncBS $ encode req)
                   hPutFlush (rpcRequestW server) msg
      , get = do verifyScope
                 mapIOToExternal server $ do
                   Response resp <- nextInStream (rpcResponseR server)
                   Ex.evaluate $ decode (unIncBS resp)
      }

illscopedConversationException :: Ex.IOException
illscopedConversationException =
  userError "Attempt to use RPC conversation outside its scope"

-- | Shut down the RPC server
--
-- This simply kills the remote process. If you want to shut down the remote
-- process cleanly you must implement your own termination protocol before
-- calling 'shutdown'.
shutdown :: RpcServer -> IO ()
shutdown server = withRpcServer server False $ \_ -> do
  writeFile "/tmp/modify31" "asdf"
  terminate server
  writeFile "/tmp/modify32" "asdf"
  let ex = Ex.toException (userError "Manual shutdown")
  return (RpcStopped ex, ())

-- | Force shutdown.
--
-- In order to faciliate a force shutdown while another thread may be
-- communicating with the RPC server, we _try_ to update the MVar underlying
-- the RPC server, but if we fail, we terminate the server anyway. This means
-- that this may leave the 'RpcServer' in an invalid state -- so you shouldn't
-- be using it anymore after calling forceShutdown!
forceShutdown :: RpcServer -> IO ()
forceShutdown server = Ex.mask_ $ do
  writeFile "/tmp/modify4pre1" "asdf"
  mst <- tryTakeMVar (rpcState server)

  writeFile "/tmp/modify4" "asdf"
  ignoreAllExceptions $ forceTerminate server
  writeFile "/tmp/modify5" "asdf"
  let ex = Ex.toException (userError "Forced manual shutdown")

  case mst of
    Nothing -> -- We failed to take the MVar. Shrug.
      return ()
    Just _ ->
      $putMVar (rpcState server) (RpcStopped ex)
  writeFile "/tmp/modify5pos1" "asdf"

-- | Silently ignore all exceptions
ignoreAllExceptions :: IO () -> IO ()
ignoreAllExceptions = Ex.handle ignore
  where
    ignore :: Ex.SomeException -> IO ()
    ignore _ = return ()

-- | Terminate the RPC connection
--
-- If we connected using 'forkRpcServer' (rather than 'connectToRpcServer')
-- we wait for the remote process to terminate.
terminate :: RpcServer -> IO ()
terminate server = do
    writeFile "/tmp/modify41" "asdf"
    ignoreIOExceptions $ hPutFlush (rpcRequestW server) (encode RequestShutdown)
    writeFile "/tmp/modify42" "asdf"
    case rpcProc server of
      Just ph -> void $ waitForProcess ph
      Nothing -> return ()
    writeFile "/tmp/modify43" "asdf"

-- | Force-terminate the external process
--
-- Throws an exception when we are connected to an existing RPC server
forceTerminate :: RpcServer -> IO ()
forceTerminate server =
    case rpcProc server of
      Just ph ->
        withProcessHandle ph $ \p_ ->
          case p_ of
            ClosedHandle _ -> do
              writeFile "/tmp/modify6" "asdf"
              res <- leaveHandleAsIs p_
              writeFile "/tmp/modify7" "asdf"
              return res
            OpenHandle pID -> do
              writeFile "/tmp/modify8" "asdf"
              signalProcess sigKILL pID
              writeFile "/tmp/modify9" "asdf"
              res <- leaveHandleAsIs p_
              writeFile "/tmp/modify10" "asdf"
              return res
      Nothing ->
        Ex.throwIO $ userError "forceTerminate: parallel connection"
  where
    leaveHandleAsIs _p =
#if MIN_VERSION_process(1,2,0)
      return ()
#else
      return (_p, ())
#endif

-- | Like modifyMVar, but terminate the server on exceptions
withRpcServer :: RpcServer -> Bool
              -> (RpcClientSideState -> IO (RpcClientSideState, a))
              -> IO a
withRpcServer server debugg io =
  Ex.mask $ \restore -> do
    when debugg $ writeFile "/tmp/modify21" "asdf"
    st <- $takeMVar (rpcState server)
    when debugg $ writeFile "/tmp/modify22" "asdf"

    mResult <- Ex.try $ restore (io st)
    when debugg $ writeFile "/tmp/modify23" "asdf"

    case mResult of
      Right (st', a) -> do
        when debugg $ writeFile "/tmp/modify24" "asdf"
        $putMVar (rpcState server) st'
        when debugg $ writeFile "/tmp/modify25" "asdf"
        return a
      Left ex -> do
   --     terminate server
        when debugg $ writeFile "/tmp/modify26" "asdf"
        $putMVar (rpcState server) (RpcStopped ex)
        when debugg $ writeFile "/tmp/modify27" "asdf"
        Ex.throwIO ex

-- | Get the exit code of the RPC server, unless still running.
--
-- Thross an exception for connections to existing RPC servers.
getRpcExitCode :: RpcServer -> IO (Maybe ExitCode)
getRpcExitCode RpcServer{rpcProc} =
  case rpcProc of
    Just ph -> getProcessExitCode ph
    Nothing -> Ex.throwIO $ userError "getRpcExitCode: parallel connection"

{------------------------------------------------------------------------------
  Aux
------------------------------------------------------------------------------}

-- | Map IO exceptions to external exceptions, using the error written
-- by the server (if any)
mapIOToExternal :: RpcServer -> IO a -> IO a
mapIOToExternal server p = Ex.catch p $ \ex -> do
  let _ = ex :: Ex.IOException
  merr <- BSL.unpack <$> BSL.hGetContents (rpcErrorsR server)
  if null merr
    then Ex.throwIO (serverKilledException (Just ex))
    else Ex.throwIO (ExternalException merr (Just ex))
